class FriendsModel {
  final String name;
  final String avatarimage;

  FriendsModel({
    required this.name,
    required this.avatarimage,
  });
}

List<FriendsModel> friendsdata = [
  FriendsModel(name: "Mandeep",
      avatarimage: "assets/images/rich_girl.jpg",
  ),
  FriendsModel(name: "Ekam",
    avatarimage: "assets/images/girls(1).jpg",
  ),
  FriendsModel(name: "Hargun",
    avatarimage: "assets/images/girls(2).jpg",
  ),
  FriendsModel(name: "Manpreet",
    avatarimage: "assets/images/girls(3).jpg",
  ),
  FriendsModel(name: "Gurpreet",
    avatarimage: "assets/images/girls(4).jpg",
  ),
  FriendsModel(name: "Richa",
    avatarimage: "assets/images/girls(5).jpg",
  ),
  FriendsModel(name: "Ritik",
    avatarimage: "assets/images/boys(1).jpg",
  ),
  FriendsModel(name: "Kulveer",
    avatarimage: "assets/images/boys(2).jpg",
  ),
  FriendsModel(name: "Prabhjot",
    avatarimage: "assets/images/boys(3).jpg",
  ),
  FriendsModel(name: "Surinder",
    avatarimage: "assets/images/boys(4).jpg",
  ),
  FriendsModel(name: "Baljinder",
    avatarimage: "assets/images/boys(4).jpg",
  ),
  FriendsModel(name: "Jaspreet",
    avatarimage: "assets/images/boys(2).jpg",
  ),
  FriendsModel(name: "Raman",
    avatarimage: "assets/images/boys(7).jpg",
  ),
  FriendsModel(name: "Davinder",
    avatarimage: "assets/images/boys(4).jpg",
  ),
  FriendsModel(name: "Hardeep",
    avatarimage: "assets/images/boys(2).jpg",
  ),
  FriendsModel(name: "Mandeep",
    avatarimage: "assets/images/rich_girl.jpg",
  ),
  FriendsModel(name: "Ekam",
    avatarimage: "assets/images/girls(1).jpg",
  ),
  FriendsModel(name: "Hargun",
    avatarimage: "assets/images/girls(2).jpg",
  ),
  FriendsModel(name: "Manpreet",
    avatarimage: "assets/images/girls(3).jpg",
  ),
  FriendsModel(name: "Gurpreet",
    avatarimage: "assets/images/girls(4).jpg",
  ),
  FriendsModel(name: "Richa",
    avatarimage: "assets/images/girls(5).jpg",
  ),
];